export type OfficialProgrammingArchiveSeed = {
  id: string;
  year: number;
  season: string;
  level: "Közép" | "Emelt";
  title: string;
  programPdfHref: string;
  programZipHref?: string;
  taskSheetPdfHref?: string;
  solutionZipHref?: string;
  family?: string;
  note?: string;
  workspaceTaskId?: string;
  fileHighlights?: string[];
  additionalAssets?: Array<{
    label: string;
    href: string;
  }>;
};

export const officialProgrammingArchiveSeeds: OfficialProgrammingArchiveSeed[] = [
  {
    id: "2025-oktober-kozep-forgalomszamlalas",
    year: 2025,
    season: "október",
    level: "Közép",
    title: "Forgalomszámlálás",
    family: "idősoros adatelemzés",
    note: "Közép szintű gyűjtés, összesítés és outputfegyelem mintája.",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2025/10/25okd_Forgalomszamlalas.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2025/10/25okd_Forgalomszamlalas.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/10/25okd_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2025/10/25okd_ut.zip",
  },
  {
    id: "2025-majus-idegen-kozep-liftvezerlo",
    year: 2025,
    season: "május idegen",
    level: "Közép",
    title: "Liftvezérlő",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/25ikd_Liftvezerlo.pdf",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/25ikd_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2025/05/25ikd_ut.zip",
  },
  {
    id: "2025-majus-kozep-kihivas",
    year: 2025,
    season: "május",
    level: "Közép",
    title: "Kihívás",
    family: "állapotfrissítés és egyszerű szimuláció",
    note: "Arra jó példa, hogyan lehet friss szövegezéssel ugyanazt a gondolkodási mintát tanítani.",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/25mkd_Kihivas.pdf",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/25mkd_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2025/05/25mkd_ut.zip",
  },
  {
    id: "2024-oktober-kozep-befozes",
    year: 2024,
    season: "október",
    level: "Közép",
    title: "Befőzés",
    family: "feldolgozás és szabályalkalmazás",
    note: "Klasszikus közép minták: parsing, ciklus, feltétel, végső kiírás.",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2024/10/24okd_Befozes.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2024/10/24okd_Befozes.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/24okd_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2024/10/24okd_ut.zip",
  },
  {
    id: "2024-majus-idegen-kozep-szolanc",
    year: 2024,
    season: "május idegen",
    level: "Közép",
    title: "Szólánc",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2024/05/24ikd_Szolanc.pdf",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/24ikd_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2024/05/24ikd.zip",
  },
  {
    id: "2024-majus-kozep-letra",
    year: 2024,
    season: "május",
    level: "Közép",
    title: "Létra",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2024/05/24mkd_Letra.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2024/05/24mkd_Letra.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/24mkd_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2024/05/24mkd_ut.zip",
  },
  {
    id: "2023-oktober-kozep-szallitas",
    year: 2023,
    season: "október",
    level: "Közép",
    title: "Szállítás",
    family: "állapotkezelés és összesítés",
    note: "Átmenet a közép nehezebb rutinjaihoz.",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2023/10/23okd_Szallitas.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2023/10/23okd_Szallitas.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/23okd_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2023/10/23okd_ut.zip",
  },
  {
    id: "2023-majus-idegen-kozep-taj-szam",
    year: 2023,
    season: "május idegen",
    level: "Közép",
    title: "TAJ-szám",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2023/06/23ikd_TAJ-szam.pdf",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/23ikd_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2023/06/23ikd_ut.zip",
  },
  {
    id: "2023-majus-kozep-kitalalo",
    year: 2023,
    season: "május",
    level: "Közép",
    title: "Kitaláló",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2023/06/23mkd_Kitalalo.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2023/06/23mkd_Kitalalo.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/23mkd_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2023/06/23mkd_ut.zip",
  },
  {
    id: "2022-oktober-kozep-kockak",
    year: 2022,
    season: "október",
    level: "Közép",
    title: "Kockák",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2022/10/22okd_Kockak.pdf",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/22okd_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2022/10/22okd_ut.zip",
  },
  {
    id: "2022-majus-idegen-kozep-fogyokura",
    year: 2022,
    season: "május idegen",
    level: "Közép",
    title: "Fogyókúra",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2022/07/22ikd_Fogyokura.pdf",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/22ikd_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2022/07/22idk_ut.zip",
  },
  {
    id: "2022-majus-kozep-robot",
    year: 2022,
    season: "május",
    level: "Közép",
    title: "Robot",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2022/07/22mkd_Robot.pdf",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/22mkd_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2022/07/22mkd_ut.zip",
  },
  {
    id: "2021-minta-kozep-szamolo",
    year: 2021,
    season: "minta",
    level: "Közép",
    title: "Számoló",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2022/07/21mkd_Szamolo.pdf",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/21mkd_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2022/07/21mkd_ut.zip",
  },
  {
    id: "2025-oktober-emelt-sebesseg",
    year: 2025,
    season: "október",
    level: "Emelt",
    title: "Sebesség",
    family: "mozgásszimuláció és számítás",
    note:
      "Koordináta, állapot és következetes szabálykezelés emelten. A workspace-be helyben letöltöttük a PDF-et, a ZIP-et és a kicsomagolt ut.txt mintafájlt is.",
    workspaceTaskId: "2025-oktober-emelt-sebesseg",
    fileHighlights: [
      "A hivatalos ZIP csomag a 3_Sebesseg/ut.txt adatfájlt tartalmazza.",
      "A PDF-ből megerősíthető, hogy ez a feladat valódi fájlos beolvasást igényel.",
    ],
    additionalAssets: [
      {
        label: "Helyi PDF",
        href: "/archive/2025-oktober-emelt/sebesseg/25oed_Sebesseg.pdf",
      },
      {
        label: "Helyi ZIP",
        href: "/archive/2025-oktober-emelt/sebesseg/25oed_Sebesseg.zip",
      },
      {
        label: "Kicsomagolt ut.txt",
        href: "/archive/2025-oktober-emelt/sebesseg/3_Sebesseg/ut.txt",
      },
    ],
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2025/10/25oed_Sebesseg.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2025/10/25oed_Sebesseg.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/10/25oed_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2025/10/25oed_ut.zip",
  },
  {
    id: "2025-majus-idegen-emelt-ascii-rajzok",
    year: 2025,
    season: "május idegen",
    level: "Emelt",
    title: "ASCII rajzok",
    family: "szigorúan formázott output",
    note: "A platform saját feladataiban ezt teljesen új vizuális történetekkel érdemes újraépíteni.",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/25ied_ASCII_rajzok.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2025/05/25ied_ASCII-rajzok.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/25ied_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2025/05/25ied_ut.zip",
  },
  {
    id: "2025-majus-emelt-konyvkiadas",
    year: 2025,
    season: "május",
    level: "Emelt",
    title: "Könyvkiadás",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/25med_konyvkiadas.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2025/05/25med_konyvkiadas.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/25med_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2025/05/25med_ut.zip",
  },
  {
    id: "2024-oktober-emelt-autok-mozgasa",
    year: 2024,
    season: "október",
    level: "Emelt",
    title: "Autók mozgása",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2024/10/24oed_Autok_mozgasa.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2024/10/24oed_Autok_mozgasa.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/24oed_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2024/10/24oed_ut.zip",
  },
  {
    id: "2024-majus-idegen-emelt-kraterek",
    year: 2024,
    season: "május idegen",
    level: "Emelt",
    title: "Kráterek",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2024/05/24ied_Kraterek.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2024/05/24ied_Kraterek.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/24ied_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2024/05/24ied_ut.zip",
  },
  {
    id: "2024-majus-emelt-belepteto-rendszer",
    year: 2024,
    season: "május",
    level: "Emelt",
    title: "Beléptető rendszer",
    family: "szabályrendszer és állapotkezelés",
    note: "Többlépcsős logika és feldolgozási fegyelem emeltre jellemző példája.",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2024/05/24med_Belepteto_rendszer.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2024/05/24med_Belepteto_rendszer.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/24med_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2024/05/24med_ut.zip",
  },
  {
    id: "2023-oktober-emelt-reklam",
    year: 2023,
    season: "október",
    level: "Emelt",
    title: "Reklám",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2023/11/23oed_Reklam.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2023/10/23oed_Reklam.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/23oed_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2023/10/23oed_ut.zip",
  },
  {
    id: "2023-majus-emelt-utemezes",
    year: 2023,
    season: "május",
    level: "Emelt",
    title: "Ütemezés",
    family: "sorrendkezelés és kiosztási logika",
    note: "A lecketérkép emelt ütemezési blokkjanak fontos alapmintája.",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2023/06/23med_Utemezes.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2023/06/23med_Utemezes.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/23med_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2023/06/23med_ut.zip",
  },
  {
    id: "2022-oktober-emelt-viragagyasok",
    year: 2022,
    season: "október",
    level: "Emelt",
    title: "Virágágyások",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2022/10/22oed_Viragagyasok.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2022/10/22oed_Viragagyasok.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/22oed_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2022/10/22oed_ut.zip",
  },
  {
    id: "2021-minta-emelt-kongresszus",
    year: 2021,
    season: "minta",
    level: "Emelt",
    title: "Kongresszus",
    programPdfHref: "https://farkascs.hu/wp-content/uploads/2022/07/21med_Kongresszus.pdf",
    programZipHref: "https://farkascs.hu/wp-content/uploads/2022/07/21med_Kongresszus.zip",
    taskSheetPdfHref: "https://farkascs.hu/wp-content/uploads/2025/05/21med_fl.pdf",
    solutionZipHref: "https://farkascs.hu/wp-content/uploads/2022/07/21med_ut.zip",
  },
];